# 🚀 MEMORIA Y COMPILACIÓN PARALELA DE GRADLE (Acelera compilaciones)
org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=2G -XX:+HeapDumpOnOutOfMemoryError
org.gradle.parallel=true
org.gradle.caching=true

# ANDROIDX Y MIGRACIÓN
android.useAndroidX=true
android.builtInKotlin=false
android.newDsl=false

# ⚡ REDUCCIÓN OPTIMIZADA DE RECURSOS Y MODO COMPLETO R8
android.enableR8.fullMode=true