org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
# Flags añadidos automáticamente por el migrador de Flutter
android.builtInKotlin=false
android.newDsl=false

# Optimización R8 y Recursos
android.enableR8.fullMode=true
android.enableResourceOptimizations=true